services:
  cheminv_backend:
    env_file: ".env"
    ports:
      - 5001:5000

    # Delete this in a production environment
    volumes:
      - ./backend/src:/cheminv

    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./backend/db:/var/lib/mysql
