services:
  cheminv_backend:
    env_file: ".env"
    ports:
      - "5001:5000"
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: on-failure
    volumes:
      - ./backend/src:/cheminv
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./backend/db:/var/lib/mysql
