services:
  cheminv_backend:
    env_file: ".env"
    ports:
      - 5001:5000

    # Include the volume only in development
    volumes:
      - ./backend/src:/cheminv

    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: on-failure

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

    volumes:
      - ./backend/db:/var/lib/mysql
