name: cheminv
services:
  cheminv:
    ports:
      - 5001:5000
    env_file: ".env"

    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./src
          action: sync
          target: /cheminv
  mysql:
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    image: mysql:latest
    volumes:
      - ./db:/var/lib/mysql

networks: {}
