name: cheminv
services:
  cheminv:
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 5000:5000
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=cheminv
    build:
      context: .
      dockerfile: Dockerfile
  mysql:
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=cheminv
    ports:
      - "3307:3306"
    image: mysql:latest
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks: {}
